name: Auto Update ThienDinh

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Thêm dòng này để chắc chắn có quyền ghi
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Cập nhật lên v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run bot
        run: python bot.py

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add thiendinh.m3u
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Update ThienDinh: $(date)"
            git push
          fi
